# SUMMARY MEMORY AGENT 🎭
import os
from datetime import datetime
from gtts import gTTS
import sounddevice as sd
import soundfile as sf
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# ───────────────────────────────────────────
# TTS - HINDI VOICE
# ───────────────────────────────────────────
def speak(text):
    print(f"Bot: {text}")
    tts = gTTS(text=text, lang="hi", slow=False)
    tts.save("temp_audio.mp3")
    os.system("ffmpeg -y -i temp_audio.mp3 temp_audio.wav -loglevel quiet")
    data, samplerate = sf.read("temp_audio.wav")
    sd.play(data, samplerate)
    sd.wait()
    os.remove("temp_audio.mp3")
    os.remove("temp_audio.wav")

# ───────────────────────────────────────────
# PDF GENERATOR
# ───────────────────────────────────────────
def generate_pdf(summary):
    filename = f"henry_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("title", parent=styles["Title"],
        textColor=colors.HexColor("#8B0000"), fontSize=22, spaceAfter=10)
    story.append(Paragraph("Horrid Henry - Summary Memory Report", title_style))
    story.append(Spacer(1, 10))

    date_style = ParagraphStyle("date", parent=styles["Normal"], textColor=colors.grey, fontSize=10)
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", date_style))
    story.append(Spacer(1, 20))
    story.append(Paragraph("<hr/>", styles["Normal"]))
    story.append(Spacer(1, 10))
    story.append(Paragraph("What Henry Remembers:", styles["Heading2"]))
    story.append(Spacer(1, 10))

    if summary:
        events = summary.split(" | ")
        for i, event in enumerate(events, 1):
            event_style = ParagraphStyle("event", parent=styles["Normal"],
                fontSize=11, spaceAfter=6, leftIndent=20)
            story.append(Paragraph(f"{i}. {event}", event_style))
    else:
        story.append(Paragraph("Koi yaadein nahi hain abhi tak!", styles["Normal"]))

    story.append(Spacer(1, 20))
    story.append(Paragraph("<hr/>", styles["Normal"]))
    footer_style = ParagraphStyle("footer", parent=styles["Normal"], textColor=colors.grey, fontSize=9)
    story.append(Paragraph("Generated by Horrid Henry Summary Memory Agent", footer_style))
    doc.build(story)
    return filename

# ───────────────────────────────────────────
# HENRY KE EVENTS
# ───────────────────────────────────────────
SUMMARY_FILE = "summary_memory.txt"

henry_events = [
    ("henry",           "Henry ne Peter ke biscuit chura liye aur Fluffy billi par ilzaam laga diya!"),
    ("peter",           "Perfect Peter ko phir se gold star mila! Henry gusse se lal ho gaya! Itna gussa aaya ke usne Peter ki diary faad di!"),
    ("mum",             "Mummy ne Henry ko kamra saaf karne kaha. Henry ne seedha mana kar diya aur bhaag gaya! Mummy abhi bhi dhundh rahi hai!"),
    ("dad",             "Papa ne Henry ko sabzi khilane ki koshish ki. Henry ne sabzi Peter pe phenk di! Papa ka chehra dekhe layak tha!"),
    ("miss battle",     "Miss Battle-Axe ne Henry ko iss saal 99waan detention diya! Henry ne kaha record tod diya, proud hoon main!"),
    ("purple hand",     "Purple Hand Gang ki secret meeting hui. Peter join karna chahta tha. Henry ne kaha KABHI NAHI! Peter roya, Henry hansa!"),
    ("ralph",           "Rude Ralph aur Henry ne stink bombs banaye aur Peter ke kamre mein rakh diye! Poora ghar bhaag gaya!"),
    ("school",          "Henry ne school chhod ke poora din Mutant Max dekha. Zindagi ka sabse accha din! Teacher ne notice hi nahi kiya!"),
    ("party",           "Henry ne party shuru hone se pehle hi saara birthday cake kha liya! Sirf crumbs bache the baaki logo ke liye!"),
    ("fluffy",          "Henry ne Fluffy ko tricks sikhane ki koshish ki. Fluffy ne nochha aur chal diya! Fluffy bhi Henry se tang aa gayi!"),
    ("homework",        "Henry ne poora homework Fluffy pe daal diya! Teacher ne pucha toh bola - billi ne kha liya madam! Sach mein!"),
    ("tv",              "Henry ne remote chhupa diya taaki sirf Mutant Max chale! Ghar mein 3 ghante koi aur channel nahi dekh paya!"),
    ("money",           "Henry ne Peter ki piggy bank se paisa chura ke pizza order kiya! Akela khaya, kisi ko bataya nahi!"),
    ("neighbour",       "Next door wale uncle ki car pe Henry ne accidentally football maar diya! Bhaag ke sofa ke neeche chhupp gaya 2 ghante!"),
    ("dentist",         "Dentist ke paas jaane se bachne ke liye Henry ne fake toothache band kar liya! Doctor ne pakad liya aur double check kiya!"),
    ("library",         "Henry ne library ki saari horror books chhuupa di taaki koi aur na padhe! Librarian abhi tak dhundh rahi hai!"),
    ("swimming",        "Swimming class mein Henry ne Peter ko pool mein dhakka diya! Coach ne Henry ko bench pe bitha diya poori class!"),
    ("report card",     "Henry ka report card aaya! Teacher ne likha - Henry mein bohot potential hai, agar woh use kare toh! Henry ne report card sofa ke neeche chhuupa diya!"),
    ("bhaad me jao",    "Kya bola Henry ko?! Tu jaanta nahi, main hun Purple Hand Gang ka supreme leader! Kalluuuu Kaliyaaaaaa! Teri khair nahi!"),
    ("maine kaha sone jao", "Hahahahahahaha! Mummy kehti hai sone jao, par ye log nahi jaante! Main ab Henry nahi hun, main hun kallu kaaliya! Neend? Woh kya hoti hai!"),
    ("kallu",           "kallu kalliyaa ka naam liya?! Kaanp! Main hun sabse bada villain! Henry toh sirf mera chota sa avatar tha!"),
    ("bhook",           "Henry ko bohot bhook lagi toh usne Peter ka tiffin bhi kha liya! Apna bhi, Peter ka bhi! Peter bhukha raha aur Henry ne belch kiya!"),
    ("cricket",         "Henry ne cricket mein cheating ki aur khud ko out hone ke baad bhi batting karte raha! Team ne usse maidan se bhaga diya!"),
    ("superhero",       "Henry ne socha woh superhero hai aur cape pahan ke sofa se kood gaya! Gira, chot lagi, phir bhi bola - main theek hoon, yeh toh training thi!"),
    ("exam",            "Exam mein Henry ne Peter ki copy karne ki koshish ki! Peter ne apni sheet chhuupa li! Henry ne guess kiya aur saare jawab galat aaye!"),
]
def get_henry_response(user_input):
    user_lower = user_input.lower()
    for keyword, response in henry_events:
        if keyword in user_lower:
            return response
    return "UGHHH! Yeh bilkul bhi theek nahi hai! Koi Henry ko nahi samajhta!"

# ───────────────────────────────────────────
# SUMMARY MEMORY FUNCTIONS
# ───────────────────────────────────────────
def load_summary():
    try:
        with open(SUMMARY_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    except FileNotFoundError:
        return ""

def save_summary(summary):
    with open(SUMMARY_FILE, "w", encoding="utf-8") as f:
        f.write(summary)

def update_summary(old_summary, user_input, bot_reply):
    if old_summary == "":
        return f"Henry ne baat ki: {user_input}. Bot ne kaha: {bot_reply}"
    return old_summary + f" | Phir Henry ne baat ki: {user_input}."

# ───────────────────────────────────────────
# MAIN AGENT
# ───────────────────────────────────────────
summary_memory = load_summary()

speak("Theek hai! Horrid Henry Summary Memory Agent chalu ho gaya!")
print("\n==Horrid Henry - Summary Memory Agent==")
print("Type 'summary'  → Henry ki yaadein sunna")
print("Type 'pdf'      → Summary ka PDF banao")
print("Type 'exit'     → Bahar jaao")
print("Try: henry, peter, mum, dad, school, party, ralph...\n")

while True:
    user_ip = input("You: ")

    if user_ip.lower() == "exit":
        speak("FINALLY! Main AZAAD ho gaya! Sayonara Sensei!")
        break

    elif user_ip.lower() == "summary":
        if summary_memory == "":
            speak("Henry ko kuch yaad nahi! Abhi tak baat hi nahi hui!")
        else:
            speak(f"Henry ki yaadein yeh hain: {summary_memory}")

    elif user_ip.lower() == "pdf":
        if summary_memory == "":
            speak("Koi yaadein nahi hain! Pehle kuch baat karo Henry se!")
        else:
            pdf_file = generate_pdf(summary_memory)
            speak("PDF ban gayi!")
            print(f"✅ PDF saved: {pdf_file}\n")

    else:
        bot_reply = get_henry_response(user_ip)
        summary_memory = update_summary(summary_memory, user_ip, bot_reply)
        save_summary(summary_memory)
        speak(bot_reply)
        print("<-- Summary Memory Update ho gayi! -->\n")